# Generated by Django 5.2.5 on 2025-09-06 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0002_add_tenant_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                (
                    "conversion_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "click",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.clickevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImpressionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("user_id", models.BigIntegerField()),
                ("cost", models.DecimalField(decimal_places=4, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="campaigns.ad"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clickevent",
            name="impression",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.impressionevent"
            ),
        ),
    ]
