# Generated by Django 5.2.5 on 2025-09-06 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0002_add_tenant_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="BidRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("request_id", models.CharField(max_length=100, unique=True)),
                ("user_id", models.BigIntegerField()),
                ("placement_id", models.CharField(max_length=100)),
                ("floor_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BidResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("bid_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("won", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bid_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bidding.bidrequest",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
    ]
