    version: "3.9"
    services:
      mysql:
        image: mysql:8.0
        environment:
          MYSQL_DATABASE: adtech_local
          MYSQL_ROOT_PASSWORD: password
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql
    
      redis:
        image: redis:7
        ports:
          - "6379:6379"
    volumes:
      mysql_data: