# Generated by Django 5.2.5 on 2025-09-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertisers", "0001_initial"),
        ("audiences", "0001_initial"),
        ("creatives", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisers.advertiser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("creative_url", models.URLField()),
                ("target_audience", models.CharField(max_length=100)),
                (
                    "audience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audiences.audiencesegment",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creatives.creative",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Impression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("user_id", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("cost", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="campaigns.ad",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant_id", "status"], name="campaigns_c_tenant__09fbf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant_id", "start_date"],
                name="campaigns_c_tenant__da5169_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="unique_campaign_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="impression",
            index=models.Index(
                fields=["tenant_id", "timestamp"], name="campaigns_i_tenant__4f5057_idx"
            ),
        ),
    ]
