# Generated by Django 5.2.5 on 2025-09-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("stopped", "Stopped"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
