# Generated by Django 5.2.5 on 2025-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant_id", "status"], name="campaigns_c_tenant__09fbf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant_id", "start_date"],
                name="campaigns_c_tenant__da5169_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="impression",
            index=models.Index(
                fields=["tenant_id", "timestamp"], name="campaigns_i_tenant__4f5057_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="unique_campaign_name_per_tenant"
            ),
        ),
    ]
