# Generated by Django 5.2.5 on 2025-09-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("event_type", models.CharField(max_length=50)),
                ("aggregate_id", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sequence_number", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AdvertiserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Creative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("asset_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="CampaignMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(db_index=True)),
                ("date", models.DateField()),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("conversions", models.BigIntegerField(default=0)),
                ("spend", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
    ]
